apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-master

resources:
- targeting-service.yaml

# Fonte de verdade da imagem. O CI reescreve estas duas linhas com
# "kustomize edit set image" — ver docs/CD-GITOPS.md.
images:
- name: targeting-service
  newName: 696500328658.dkr.ecr.us-east-1.amazonaws.com/togglemaster/targeting-service
  newTag: 949d15fe8b2c6b47849131d828def8df0c8c2663
